import java.io.File;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

/**
 * Class Main
 * Processes the input files generated by GenerateInfoFiles and creates reports in TXT and CSV formats.
 */
public class Main {
    public static void main(String[] args) {
        try {
            File outputDir = new File("output");
            if (!outputDir.exists()) {
                outputDir.mkdirs();
            }

            Path inputPath = Paths.get("input/data.txt");
            List<String> lines = Files.readAllLines(inputPath);

            // --- TXT Report ---
            PrintWriter txtReport = new PrintWriter("output/report.txt", "UTF-8");
            for (String line : lines) {
                txtReport.println("Processed: " + line);
            }
            txtReport.close();

            // --- CSV Report ---
            PrintWriter csvReport = new PrintWriter("output/report.csv", "UTF-8");
            csvReport.println("Product;Price;Status");
            for (String line : lines) {
                String[] parts = line.split(",");
                String product = parts[0].trim();
                String price = parts.length > 1 ? parts[1].trim() : "N/A";
                csvReport.println(product + ";" + price + ";Processed");
            }
            csvReport.close();

            System.out.println("Main: Reports successfully created in ./output");
        } catch (Exception e) {
            System.err.println("Error in Main: " + e.getMessage());
        }
    }
}
